version: '3.8'
services:
    zipkin:
        image: openzipkin/zipkin-slim
        ports:
            - "9411:9411"
        networks:
            - otel-network
    jaeger:
        image: jaegertracing/all-in-one
        environment:
            COLLECTOR_ZIPKIN_HOST_PORT: 9412
        ports:
            - "9412:9412"
            - "16686:16686"
        networks:
            - otel-network
    app:
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
            args:
                - UID=${UID}
                - USER_NAME=${USER_NAME}
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ../:/var/www:delegated
            - ../data/log/profiles:/tmp/profiles:delegated
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
            - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
        networks:
            - otel-network
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 8083:80
        volumes:
            - ../:/var/www:delegated
            - ../docker/nginx/conf.d/:/etc/nginx/conf.d/:delegated
        networks:
            - otel-network
    db:
        image: mariadb:10.4.10
        restart: unless-stopped
        tty: true
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: boilerplate
            MYSQL_ROOT_PASSWORD: 12345
        volumes:
            - dbdata:/var/lib/mysql/
            - ../docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ../docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
        networks:
            - otel-network
    composer:
        image: composer:2.2
        volumes:
            - ../:/app

    # MongoDB: https://hub.docker.com/_/mongo/
    mongo:
        image: mongo:4.2
        networks:
            - graylog
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        networks:
            - graylog
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
        image: graylog/graylog:4.3
        environment:
            # CHANGE ME (must be at least 16 characters)!
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
        networks:
            - graylog
            - otel-network
        restart: always
        depends_on:
            - mongo
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp
networks:
    otel-network:
        driver: bridge
    graylog:
        driver: bridge
volumes:
    dbdata:
        driver: local
